import turtle
myTurtle = turtle.Turtle()
myTurtle.speed(0)
myTurtle.color("BLUE")
myTurtle.pencolor("BLUE")
myTurtle.pensize(5)
# 배
myTurtle.penup()
myTurtle.setposition(-5, -50)
myTurtle.pendown()

myTurtle.circle(60)


# 얼굴 안쪽선
myTurtle.penup()
myTurtle.setposition(-13, 50)
myTurtle.pendown()
myTurtle.fillcolor("white")
myTurtle.begin_fill()
myTurtle.circle(95)
myTurtle.end_fill()
# 오른쪽눈
myTurtle.penup()
myTurtle.setposition(0, 200)
myTurtle.forward(20)
myTurtle.pendown()
myTurtle.fillcolor("white")
myTurtle.begin_fill()
myTurtle.circle(30)
myTurtle.end_fill()
# 오른쪽눈 눈동자
myTurtle.penup()
myTurtle.setposition(8, 220)
myTurtle.pendown()
myTurtle.fillcolor("BLUE")
myTurtle.begin_fill()
myTurtle.circle(5)
myTurtle.end_fill()
# 왼쪽눈
myTurtle.penup()
myTurtle.setposition(17, 200)
myTurtle.backward(60)
myTurtle.pendown()
myTurtle.fillcolor("white")
myTurtle.begin_fill()
myTurtle.circle(30)
myTurtle.end_fill()
myTurtle.penup()
myTurtle.setposition(-30, 220)
myTurtle.pendown()
# 왼쪽눈 눈동자
myTurtle.fillcolor("BLUE")
myTurtle.begin_fill()
myTurtle.circle(5)
myTurtle.end_fill()
# 코
myTurtle.penup()
myTurtle.setposition(-12, 195)
myTurtle.pendown()
myTurtle.circle(12)
# 인중
myTurtle.right(90)
myTurtle.forward(60)
# 입
myTurtle.right(90)
myTurtle.forward(50)
myTurtle.setposition(-60, 120)
myTurtle.setposition(-50, 100)
myTurtle.setposition(-40, 90)
myTurtle.setposition(-35, 85)
myTurtle.setposition(-30, 82)
myTurtle.setposition(-25, 80)
myTurtle.setposition(-5, 80)
myTurtle.setposition(0, 80)
myTurtle.setposition(5, 82)
myTurtle.setposition(10, 85)
myTurtle.setposition(15, 90)
myTurtle.setposition(20, 95)
myTurtle.setposition(25, 100)
myTurtle.setposition(30, 110)
myTurtle.setposition(32, 115)
myTurtle.setposition(34, 120)
myTurtle.setposition(35, 135)
myTurtle.forward(50)
# 겉얼굴
myTurtle.penup()
myTurtle.setposition(-15, 290)
myTurtle.pendown()
myTurtle.circle(120)
# 수염
myTurtle.penup()
myTurtle.setposition(-40, 190)
myTurtle.pendown()
myTurtle.right(20)
myTurtle.forward(80)
myTurtle.penup()
myTurtle.setposition(15, 190)
myTurtle.pendown()
myTurtle.right(145)
myTurtle.forward(80)
myTurtle.penup()
myTurtle.setposition(15, 170)
myTurtle.pendown()
myTurtle.right(15)
myTurtle.forward(80)
myTurtle.penup()
myTurtle.setposition(-40, 170)
myTurtle.pendown()
myTurtle.right(180)
myTurtle.forward(80)
myTurtle.penup()
myTurtle.setposition(-40, 150)
myTurtle.pendown()
myTurtle.left(20)
myTurtle.forward(80)
myTurtle.penup()
myTurtle.setposition(15, 150)
myTurtle.pendown()
myTurtle.left(145)
myTurtle.forward(80)
# 오른쪽 팔
myTurtle.penup()
myTurtle.setposition(90, 105)
myTurtle.pendown()
myTurtle.setposition(100, 80)
myTurtle.setposition(110, 50)
myTurtle.setposition(105, 30)
myTurtle.setposition(100, 0)
myTurtle.penup()
myTurtle.setposition(85, -30)
myTurtle.pendown()
myTurtle.circle(18)
# 오른쪽 몸통선
myTurtle.penup()
myTurtle.setposition(63, 55)
myTurtle.pendown()
myTurtle.right(70)
myTurtle.forward(80)
myTurtle.right(5)
myTurtle.forward(40)
# 왼쪽 팔
myTurtle.penup()
myTurtle.setposition(-100, 90)
myTurtle.pendown()
myTurtle.setposition(-100, 30)
myTurtle.setposition(-105, 0)
myTurtle.penup()
myTurtle.setposition(-110, -13)
myTurtle.pendown()
myTurtle.circle(18)
myTurtle.penup()
myTurtle.setposition(-70, 50)
myTurtle.pendown()
myTurtle.forward(60)
myTurtle.left(5)
myTurtle.forward(60)
# 왼쪽 발
myTurtle.setposition(-45, -60)
myTurtle.setposition(-20, -60)
myTurtle.setposition(0, -70)
myTurtle.setposition(0, -80)
myTurtle.setposition(-20, -90)
myTurtle.setposition(-45, -90)
myTurtle.setposition(-65, -75)
# 오른쪽 발
myTurtle.penup()
myTurtle.setposition(70, -65)
myTurtle.pendown()
myTurtle.right(125)
myTurtle.forward(20)
myTurtle.left(20)
myTurtle.forward(20)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.left(80)
myTurtle.forward(20)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.forward(10)
myTurtle.forward(10)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.left(20)
myTurtle.forward(10)
myTurtle.left(70)
myTurtle.forward(10)
# 주머니
myTurtle.penup()
myTurtle.setposition(30, 30)
myTurtle.pendown()
myTurtle.left(60)
myTurtle.forward(70)
myTurtle.left(90)
for i in range(17):
    myTurtle.left(10)
    myTurtle.forward(6)

myTurtle.penup()
myTurtle.setposition(30, 30)
myTurtle.pendown()

turtle.done()
