import turtle
myTurtle = turtle.Turtle()
myTurtle.forward(100)
myTurtle.right(60)
myTurtle.forward(100)
myTurtle.right(60)
myTurtle.forward(100)
myTurtle.right(60)
myTurtle.forward(100)
myTurtle.right(60)
myTurtle.forward(100)
myTurtle.right(60)
myTurtle.forward(100)

turtle.done()
